// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHQsdPW4HfIT1DFjlX3MpXdFkJ0ZEbGA',
    appId: '1:558502426662:web:0fdba32bea1a4308918ee7',
    messagingSenderId: '558502426662',
    projectId: 'collage-campus-app-aa339',
    authDomain: 'collage-campus-app-aa339.firebaseapp.com',
    storageBucket: 'collage-campus-app-aa339.firebasestorage.app',
    measurementId: 'G-2EZ2B7YCT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJe-LH2Tedt9ZAOcPCL5KYNyFAkZ3BG0',
    appId: '1:558502426662:android:2aa3ea93d51e0438918ee7',
    messagingSenderId: '558502426662',
    projectId: 'collage-campus-app-aa339',
    storageBucket: 'collage-campus-app-aa339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVreBa8R3AyISrDU4iuxDizMOskrFRWo',
    appId: '1:558502426662:ios:2fbe8dee57cdd757918ee7',
    messagingSenderId: '558502426662',
    projectId: 'collage-campus-app-aa339',
    storageBucket: 'collage-campus-app-aa339.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVreBa8R3AyISrDU4iuxDizMOskrFRWo',
    appId: '1:558502426662:ios:2fbe8dee57cdd757918ee7',
    messagingSenderId: '558502426662',
    projectId: 'collage-campus-app-aa339',
    storageBucket: 'collage-campus-app-aa339.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
